export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES';
export const GET_SINGLE_ARTICLE = 'GET_SINGLE_ARTICLE';
export const NEW_ARTICLE_SUBMITTED = 'NEW_ARTICLE_SUBMITTED';
export const ERROR_SUBMITTING_ARTICLE = 'ERROR_SUBMITTING_ARTICLE';
