export const GOT_ALL_ARTICLES = 'GOT_ALL_ARTICLES';
export const GOT_SINGLE_ARTICLE = 'GOT_SINGLE_ARTICLE';
export const SUBMITTED_NEW_ARTICLE = 'SUBMITTED_NEW_ARTICLE';
export const SAVED_ARTICLE = 'SAVED_ARTICLE';
export const DELETED_ARTICLE = 'DELETED_ARTICLE';

export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_ERRORS = 'LOGIN_ERRORS';